### ISSUE TITLE
Error codes enum

### ISSUE THREAD

**Issue by NELUxP** [astrelsky/GhidraOrbis#17]
[astrelsky] Can u add error codes to a Enum or something like this?
for example 
SCE_NP_ERROR_ALREADY_INITIALIZED  = 80550001h
SCE_NP_ERROR_NOT_INITIALIZED  = 80550002h
SCE_NP_ERROR_INVALID_ARGUMENT  = 80550003h
SCE_NP_ERROR_UNKNOWN_PLATFORM_TYPE  = 80550004h
SCE_NP_ERROR_OUT_OF_MEMORY  = 80550005h
SCE_NP_ERROR_SIGNED_OUT  = 80550006h
SCE_NP_ERROR_USER_NOT_FOUND  = 80550007h
SCE_NP_ERROR_CALLBACK_ALREADY_REGISTERED  = 80550008h
SCE_NP_ERROR_CALLBACK_NOT_REGISTERED  = 80550009h
SCE_NP_ERROR_NOT_SIGNED_UP  = 8055000Ah
SCE_NP_ERROR_AGE_RESTRICTION  = 8055000Bh
SCE_NP_ERROR_LOGOUT  = 8055000Ch
SCE_NP_ERROR_LATEST_SYSTEM_SOFTWARE_EXIST  = 8055000Dh
SCE_NP_ERROR_LATEST_SYSTEM_SOFTWARE_EXIST_FOR_TITLE  = 8055000Eh
SCE_NP_ERROR_LATEST_PATCH_PKG_EXIST  = 8055000Fh
SCE_NP_ERROR_LATEST_PATCH_PKG_DOWNLOADED  = 80550010h
SCE_NP_ERROR_INVALID_SIZE  = 80550011h
SCE_NP_ERROR_ABORTED  = 80550012h
SCE_NP_ERROR_REQUEST_MAX  = 80550013h
SCE_NP_ERROR_REQUEST_NOT_FOUND  = 80550014h
SCE_NP_ERROR_INVALID_ID  = 80550015h
SCE_NP_ERROR_NP_TITLE_DAT_NOT_FOUND  = 80550016h
SCE_NP_ERROR_INCONSISTENT_NP_TITLE_ID  = 80550017h
SCE_NP_ERROR_PATCH_NOT_CHECKED  = 80550018h
SCE_NP_ERROR_TITLE_IS_BANNED  = 80550019h
SCE_NP_ERROR_TIMEOUT  = 8055001Ah
SCE_NP_ERROR_TITLE_ID_IN_PARAM_SFO_NOT_MATCHED_TO_NP_TITLE_ID  = 8055001Bh
SCE_NP_ERROR_TITLE_ID_IN_PARAM_SFO_NOT_EXIST  = 8055001Ch
SCE_NP_ERROR_CALLBACK_MAX  = 8055001Dh

**Comment by astrelsky** [comment]
It should be possible to scrape them from the wiki.

**Comment by astrelsky** [comment]
On second thought it might not be a good idea, see [#4315](https://github.com/NationalSecurityAgency/ghidra/discussions/4315). Since they appear to be "unique" values it might be more effective to write a script to search for all scalar values within a range and apply the corresponding equate.

**Comment by NELUxP** [comment]
Alright thanks for answer👍
