### ISSUE TITLE
Cannot parse long from ffffffff82200000 - ghidra refuses to load the kernel

### ISSUE THREAD

**Issue by cutesmilee** [astrelsky/GhidraOrbis#8]
when I try to load the PS4 kernel (don't remember the version, should be 8.x btw) in Ghidra 10.1.1 with the latest version of the plugin which successfully loads in IDA, it gives me this error.
<img width="642" alt="Schermata 2021-12-27 alle 12 45 10" src="https://user-images.githubusercontent.com/41830087/147469339-45655227-d803-446d-838e-46927ca46b59.png">
more infos here: https://pastebin.com/izy2RFSk.

**Comment by astrelsky** [comment]
This should be fixed by #5. Does this occur when trying to change the image base or does it occur regardless?

If it is not fixed and you are unable to reopen it let me know.
